require:
  - rubocop-rails
  - rubocop-rspec
  - ./lib/cops/no_require_rails_helper.rb

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "bin/*"
    - "config/puma.rb"
    - "db/migrate/**/*.rb"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Bundler/OrderedGems:
  Enabled: false

Gemspec/DateAssignment:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment: # new in 1.30
  Enabled: false

Gemspec/RequireMFA: # new in 1.23
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/ExtraSpacing:
  AllowForAlignment: true
  AllowBeforeTrailingComments: true

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: true

Layout/SpaceAroundOperators:
  AllowForAlignment: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/LineLength:
  Max: 160

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*.rb"

Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: false

Lint/AmbiguousRange: # new in 1.19
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: false

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/EmptyInPattern: # new in 1.16
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/RefinementImportMethods: # new in 1.27
  Enabled: true

Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: true

Lint/SymbolConversion:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - "app/operations/**/*.rb"
    - "app/services/**/*.rb"
  Max: 25

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - "app/operations/**/*.rb"
    - "app/services/**/*.rb"
    - "lib/**/*.rb"

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Exclude:
    - "app/operations/**/*.rb"
    - "app/services/**/*.rb"

Naming/AccessorMethodName:
  Enabled: false

Naming/BlockForwarding: # new in 1.24
  Enabled: true

Naming/ConstantName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_
  NamePrefix:
    - is_

Naming/VariableNumber:
  Enabled: false

Rails/ActionControllerTestCase: # new in 2.14
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/AddColumnIndex: # new in 2.11
  Enabled: true

Rails/AfterCommitOverride:
  Enabled: true

Rails/AttributeDefaultBlockValue:
  Enabled: true

Rails/CompactBlank: # new in 2.13
  Enabled: true

Rails/Date:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/DeprecatedActiveModelErrorsMethods: # new in 2.14
  Enabled: true

Rails/DotSeparatedKeys: # new in 2.15
  Enabled: true

Rails/DuplicateAssociation: # new in 2.14
  Enabled: true

Rails/DuplicateScope: # new in 2.14
  Enabled: true

Rails/DurationArithmetic: # new in 2.13
  Enabled: true

Rails/EagerEvaluationLogMessage: # new in 2.11
  Enabled: true

Rails/ExpandedDateRange: # new in 2.11
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/FindById:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/I18nLazyLookup: # new in 2.14
  Enabled: true

Rails/I18nLocaleAssignment: # new in 2.11
  Enabled: true

Rails/I18nLocaleTexts: # new in 2.14
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/MigrationClassName: # new in 2.14
  Enabled: true

Rails/NegateInclude:
  Enabled: false

Rails/Pluck:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RedundantPresenceValidationOnBelongsTo: # new in 2.13
  Enabled: true

Rails/RedundantTravelBack: # new in 2.12
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/RootJoinChain: # new in 2.13
  Enabled: true

Rails/RootPublicPath: # new in 2.15
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false

Rails/StripHeredoc: # new in 2.15
  Enabled: true

Rails/TimeZoneAssignment: # new in 2.10
  Enabled: true

Rails/ToFormattedS: # new in 2.15
  Enabled: true

Rails/TransactionExitStatement: # new in 2.14
  Enabled: true

Rails/UnusedIgnoredColumns: # new in 2.11
  Enabled: true

Rails/WhereEquals:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/WhereNot:
  Enabled: true

RSpec/BeEq: # new in 2.9.0
  Enabled: true

RSpec/BeNil: # new in 2.9.0
  Enabled: true

RSpec/ChangeByZero: # new in 2.11.0
  Enabled: true

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/requests/**/*.rb

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExcessiveDocstringSpacing: # new in 2.5
  Enabled: true

RSpec/ExpectActual:
  Enabled: false

RSpec/FactoryBot/SyntaxMethods: # new in 2.7
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/IdenticalEqualityAssertion:
  Enabled: true

RSpec/ImplicitSubject:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NoRequireRailsHelper:
  Exclude:
    - spec/spec_helper.rb
    - spec/rails_helper.rb

RSpec/Rails/AvoidSetupHook:
  Enabled: true

RSpec/RepeatedDescription:
  Exclude:
    - "spec/policies/**/*.rb"

RSpec/RepeatedExample:
  Exclude:
    - "spec/policies/**/*.rb"

RSpec/SubjectDeclaration: # new in 2.5
  Enabled: true

RSpec/VerifiedDoubles:
  IgnoreNameless: true
  IgnoreSymbolicNames: true

RSpec/VerifiedDoubleReference: # new in 2.10.0
  Enabled: true

RSpec/ScatteredLet:
  Enabled: false

Security/CompoundHash: # new in 1.28
  Enabled: true

Security/IoMethods: # new in 1.22
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/ArrayJoin:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CollectionCompact:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/EndlessMethod:
  Enabled: true

Style/EnvHome: # new in 1.29
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: false

Style/FetchEnvVar: # new in 1.28
  Enabled: false

Style/FileRead: # new in 1.24
  Enabled: true

Style/FileWrite: # new in 1.24
  Enabled: true

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GuardClause:
  Enabled: false

Style/HashConversion:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/InPatternThen: # new in 1.16
  Enabled: true

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/MapCompactWithConditionalBlock: # new in 1.30
  Enabled: true

Style/MapToHash: # new in 1.24
  Enabled: true

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/MultilineInPatternThen: # new in 1.16
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NestedFileDirname: # new in 1.26
  Enabled: true

Style/Next:
  Enabled: false

Style/NilLambda:
  Enabled: true

Style/NumberedParameters: # new in 1.22
  Enabled: true

Style/NumberedParametersLimit: # new in 1.22
  Enabled: true

Style/NumericPredicate:
  Enabled: false

Style/ObjectThen: # new in 1.28
  Enabled: true

Style/OpenStructUse: # new in 1.23
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: false

# This clobbers unexpected method calls
Style/PreferredHashMethods:
  Enabled: false

Style/QuotedSymbols: # new in 1.16
  Enabled: true
  EnforcedStyle: double_quotes

Style/RaiseArgs:
  Enabled: false

Style/RedundantArgument:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: false

Style/RedundantInitialize: # new in 1.27
  Enabled: true

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: true

# Enumerable#grep is not always equivalent to x.select { |y| y.match? z }
Style/SelectByRegexp: # new in 1.22
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/StringChars:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/SwapValues:
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/UnlessElse:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false
