require:
  - rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "bin/*"
    - "config/puma.rb"
    - "db/migrate/**/*.rb"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "spec/**/*"
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Bundler/OrderedGems:
  Enabled: false

Gemspec/DateAssignment:
  Enabled: true

Layout/ArgumentAlignment:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: true
  AllowBeforeTrailingComments: true

Layout/HashAlignment:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/SpaceAroundOperators:
  AllowForAlignment: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/LineLength:
  Max: 160

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: false

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/SymbolConversion:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Naming/MethodName:
  Enabled: false

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_
  NamePrefix:
    - is_

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/AfterCommitOverride:
  Enabled: true

Rails/AttributeDefaultBlockValue:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/FindById:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/WhereEquals:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/WhereNot:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/ArrayJoin:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Style/CollectionCompact:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/EndlessMethod:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GuardClause:
  Enabled: false

Style/HashConversion:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NegatedIfElseCondition:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringChars:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/SwapValues:
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/UnlessElse:
  Enabled: false
