version: "3.9"
services:
  cache:
    image: "memcached:1.6.9"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    restart: unless-stopped
    shm_size: 2g
  db:
    image: "postgres:13.4-alpine"
    shm_size: 2g
    environment:
      POSTGRES_PASSWORD: password
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
  redis:
    image: bitnami/redis:latest
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    restart: unless-stopped
  web:
    tty: true
    stdin_open: true
    build: .
    depends_on:
      - db
      - redis
    env_file: docker/compose.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - bundle_cache:/bundle
      - .:/srv/app
    ports:
      - "6222:6222"
    restart: unless-stopped
  worker:
    build: .
    command: bin/sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - redis
    env_file: docker/compose.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - bundle_cache:/bundle
      - .:/srv/app
    restart: unless-stopped
  clock:
    build: .
    command: bin/zhong zhong.rb
    depends_on:
      - db
      - redis
    env_file: docker/compose.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - bundle_cache:/bundle
      - .:/srv/app
    restart: unless-stopped

volumes:
  bundle_cache:
    driver: local
  postgres-data:
    driver: local
