# frozen_string_literal: true

module Support
  module DryGQL
    # Types for working with dry-rb and graphql-ruby integrations.
    module Types
      extend ::Support::Typespace

      # A type matching a GraphQL enum class.
      #
      # @return [Dry::Types::Type]
      EnumType = Class.constrained(inherits: ::GraphQL::Schema::Enum)

      # A type matching an array of GraphQL enum classes.
      #
      # @return [Dry::Types::Type]
      EnumTypes = Array.of(EnumType)

      # A type matching a string that can be used to lazily load a GraphQL type from the Types namespace.
      #
      # @return [Dry::Types::Type]
      LazyLoadTypeName = String.constrained(format: /\A(?:::)?Types::[A-Z]\S+\z/)

      # A string that can be used as a key for referencing a model type.
      #
      # @return [Dry::Types::Type]
      ModelKey = Coercible::String.constrained(filled: true)

      # @see Support::Models::Types::Name
      #
      # @return [Dry::Types::Type]
      ModelName = Support::Models::Types::Name

      # @see Support::Models::Types::Names
      #
      # @return [Dry::Types::Type]
      ModelNames = Support::Models::Types::Names

      # A GraphQL query with no schema, for building query contexts.
      #
      # @api private
      NULL_QUERY = GraphQL::Query.new(::GraphQL::Schema)

      # A builder for a null query context.
      # It accepts a hash of values to set and produces a `GraphQL::Query::Context`.
      #
      # @api private
      BUILD_NULL_CONTEXT = proc do |**values|
        GraphQL::Query::Context.new(query: NULL_QUERY, values:)
      end

      # A GraphQL query context.
      #
      # It will fall back to a null context generated by {BUILD_NULL_CONTEXT} if none is provided.
      QueryContext = Instance(::GraphQL::Query::Context).default { BUILD_NULL_CONTEXT.() }

      # A type matching a `GraphQL::Schema::Member` class, which could be an object, enum, etc.
      #
      # @return [Dry::Types::Type]
      SchemaMember = Class.constrained(inherits: ::GraphQL::Schema::Member)

      # A type matching either a GraphQL::Schema::Member or a string that can be used to lazily load one.
      # @see LazyLoadTypeName
      # @see SchemaMember
      #
      # @return [Dry::Types::Type]
      TypeReference = LazyLoadTypeName | SchemaMember

      # A dry-type with GQL typing
      #
      # @return [Dry::Types::Type]
      Type = ::Support::Types::DryType.constrained(gql_typing: true)
    end
  end
end
