# frozen_string_literal: true

module Types
  # @see SubmissionTargets::Section
  # @see Types::SubmissionTargetSectionInputType
  class SubmissionTargetSectionType < Types::BaseObject
    description <<~TEXT
    An object representing a section of a submission target's description.
    TEXT

    field :identifier, String, null: false do
      description <<~TEXT
      A unique identifier for the section. This is generated by the system and should not be provided by the client.
      TEXT
    end

    field :name, String, null: false do
      description <<~TEXT
      The name of the section. This is used to identify the section and should be unique within an action.
      TEXT
    end

    field :position, Integer, null: false do
      description <<~TEXT
      The position of the section within the action's description.

      This value is automatically generated by the API.
      TEXT
    end

    field :content, String, null: false do
      description <<~TEXT
      The content of the section. This is the actual text that will be displayed for this section of the action's description.
      TEXT
    end
  end
end
