default: &default
  allow_anonymous: true
  halt_on_auth_failure: false
  realm_id: "NGLP"
  server_url: "https://auth.nglp.org/auth"

development:
  <<: *default

test:
  <<: *default
  server_url: "http://keycloak.example.com"
  realm_id: "Test"

production:
  <<: *default
