default: &default
  allow_anonymous: true
  halt_on_auth_failure: false
  realm_id: "meru"
  server_url: "https://id.sandbox.meru.host"

development:
  <<: *default

test:
  <<: *default
  server_url: "http://keycloak.example.com"
  realm_id: "Test"

production:
  <<: *default
