default: &default
#  access_key_id: ""
#  secret_access_key: ""
#  endpoint: ""
#  region: ""
#  force_path_style: ""

development:
  <<: *default
  access_key_id: minio
  secret_access_key: minio123
  endpoint: http://localhost:10042
  region: "us-east-1"
  force_path_style: true

test:
  <<: *default

production:
  <<: *default
