default: &default
  access_key_id: ""
  secret_access_key: ""
  region: "us-east-1"
  force_path_style: false

development:
  <<: *default
  endpoint: http://minio:9000
  access_key_id: minio
  secret_access_key: minio123
  region: "us-east-1"
  force_path_style: true

test:
  <<: *default
  access_key_id: minio
  secret_access_key: minio123
  region: "us-east-1"

staging:
  <<: *default
  endpoint: https://sfo3.digitaloceanspaces.com
  region: "us-east-1"
  force_path_style: true

production:
  <<: *default
  endpoint: https://sfo3.digitaloceanspaces.com
  region: "us-east-1"
  force_path_style: true
