:concurrency: 10
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
production:
  :concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
:queues:
  - default
  - permissions
  - processing
  - mailers
  - maintenance
