:concurrency: 20
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 2 } %>
production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 } %>
:queues:
  - default
  - mailers
  - permissions
  - processing
  - maintenance
  - hierarchies
  - entities
  - orderings
  - harvesting
