default: &default
  bucket: "meru-api-storage"
  cdn_host: ""
  mapped_host: ""
  public: true

development:
  <<: *default
  mapped_host: "http://localhost:6224"

test:
  <<: *default

staging:
  <<: *default
  remap_signed_url: true

production:
  <<: *default
  remap_signed_url: true
