# frozen_string_literal: true

module Support
  module Filtering
    module Inputs
      # The base class for building generic match input structs.
      #
      # @abstract
      class AbstractMatch < ::Support::FlexibleStruct
        extend Dry::Core::ClassAttributes

        include ArelHelpers

        # A type container for the comparator.
        #
        # @api private
        BASE_TYPES = Support::DryGQL::TypeContainer.new

        defines :base_type, type: ::Support::Types::DryType
        defines :type_key, type: ::Support::Types::Symbol
        defines :input_object, type: ::Support::Types::Class.optional

        base_type ::Support::Types::Any

        input_object nil

        type_key :_unset

        private

        # @see ArelHelpers#arel_and_expressions
        # @return [Arel::Expressions]
        def arel_andify(...)
          arel_and_expressions(...)
        end

        class << self
          # Build a new subclass for the given type key.
          #
          # Subclasses should inherit from the type generated by this method.
          #
          # @param [#to_s] type_key
          # @return [Class(Filtering::Inputs::ComparatorMatch)]
          def of(type_key, input_object: nil)
            type = BASE_TYPES.resolve type_key

            base_class_name = "abstract_#{type_key}_match".classify

            Class.new(self).tap do |klass|
              klass.base_type type
              klass.type_key type_key

              Support::Filtering::Inputs.const_set base_class_name, klass

              klass.on_inherit!

              # :nocov:
              klass.input_object input_object if input_object.present?
              # :nocov:
            end.with_gql_type
          end

          # @param [Hash{Symbol => Object}] ruby_kwargs
          # @return [GraphQL::Schema::InputObject]
          def build_input_object(**ruby_kwargs)
            input_object.new({}, ruby_kwargs:, context: nil, defaults_used: false)
          end

          protected

          # @abstract
          # @return [void]
          def on_inherit!; end

          # Augment the subclass with GraphQL type information.
          #
          # @note Used within {.of}.
          # @return [Class(Filtering::Inputs::AbstractMatch)]
          def with_gql_type
            gql_type(input_object)
          end
        end
      end
    end
  end
end
